# Generated by Django 5.0.4 on 2026-05-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredapp',
            name='icon_base64',
            field=models.TextField(blank=True, default=''),
        ),
    ]
